name: Deploy TrainingPlanner API to Azure

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: windows-latest
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET 10
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'

      - name: Build API
        run: dotnet build Release

      - name: Publish API
        run: dotnet publish TrainingPlanner.API/TrainingPlanner.API.csproj -c Release -o "${{ github.workspace }}/publish"

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ${{ github.workspace }}/publish

      - name: Deploy to Azure App Service
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'TrainingPlanner-backend'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}
          package: ${{ github.workspace }}/publish
